from ab_utils.smk import log_path


configfile: "smk_config.yaml"


rule tidy_aggv3_ids:
    input:
        "/mnt/file-systems/512426816668-gel-data-resources/dragen3.7.8/AggV3_resources/samples/sample_list/2026-01-23/sample_list_aggv3.csv",
    output:
        "data/interim/samples_aggv3_ids_tidy.tsv",
    log:
        log_path("tidy_aggv3_ids", workflow.snakefile),
    script:
        "tidy_aggv3_ids.py"


rule get_gel_participant:
    input:
        "/mnt/file-systems/512426816668-structured-data/100K/v19.0/2025-01-24/data/gel_participant_100k.tsv",
    output:
        relation="data/interim/samples_gel_rd_relation.tsv",
        proband="data/interim/samples_gel_rd_proband.txt",
    log:
        log_path("get_gel_participant", workflow.snakefile),
    script:
        "get_gel_participant.py"


rule get_gms_rd_affected:
    input:
        "/mnt/file-systems/512426816668-structured-data/GMS/v5.0/2025-12-17/data/gel_referral_participant_gms.tsv",
    output:
        affection="data/interim/samples_gms_rd_affection.txt",
        proband="data/interim/samples_gms_rd_proband.txt",
        relation="data/interim/samples_gms_rd_relation.tsv",
    log:
        log_path("get_gms_rd_affected", workflow.snakefile),
    script:
        "get_gms_affected.py"


# rule get_rna_bams:
#     input:
#         config["gel_rna_file_paths_new"],
#     output:
#         "data/interim/samples_gel_rna_bams.tsv",
#     log:
#         log_path("get_rna_bams", workflow.snakefile),
#     script:
#         "get_rna_bams.py"


rule get_gel_dna_bams:
    input:
        config["gel_dna_file_paths_new"],
    output:
        "data/interim/samples_gel_dna_bams.tsv",
    log:
        log_path("get_gel_dna_bams", workflow.snakefile),
    script:
        "get_gel_dna_bams.py"


rule get_gms_dna_bams:
    input:
        config["gms_dna_file_paths_new"],
    output:
        "data/interim/samples_gms_dna_bams.tsv",
    log:
        log_path("get_gms_dna_bams", workflow.snakefile),
    script:
        "get_gms_dna_bams.py"


rule catenate_relation:
    input:
        "data/interim/samples_gel_rd_relation.tsv",
        "data/interim/samples_gms_rd_relation.tsv",
    output:
        "data/interim/samples_cat_rd_relation.tsv",
    log:
        log_path("catenate_relation", workflow.snakefile),
    shell:
        """
        exec 2> >(tee {log} >&2)

        source src/utils.sh

        cat {input} \
            | tee >(_log "Unique relation:\n" "$(cut -f 2 | sort | uniq -c)") \
            | tee >(_log "Output lines:" "$(wc -l)") \
                >{output}
        """


rule catenate_proband:
    input:
        "data/interim/samples_gel_rd_proband.txt",
        "data/interim/samples_gms_rd_proband.txt",
    output:
        "data/interim/samples_cat_rd_proband.tsv",
    log:
        log_path("catenate_proband", workflow.snakefile),
    shell:
        """
        exec 2> >(tee {log} >&2)

        source src/utils.sh

        cat {input} \
            | tee >(_log "Proband value_counts:\n" "$(cut -f 2 | sort | uniq -c)") \
            | tee >(_log "Output lines:" "$(wc -l)") \
                >{output}
        """


rule catenate_dna_bams:
    input:
        "data/interim/samples_gel_dna_bams.tsv",
        "data/interim/samples_gms_dna_bams.tsv",
    output:
        "data/interim/samples_cat_dna_bams.tsv",
    log:
        log_path("catenate_dna_bams", workflow.snakefile),
    shell:
        """
        exec 2> >(tee {log} >&2)

        source src/utils.sh

        cat {input} \
            | tee >(_log "Assembly value_counts:\n" "$(cut -f 2 | sort | uniq -c)") \
            | tee >(_log "Unique participant IDs:" "$(cut -f 1 | sort -u | wc -l)") \
            | tee >(_log "Unique BAM paths:" "$(cut -f 3 | sort -u | wc -l)") \
            | tee >(_log "Output lines:" "$(wc -l)") \
                >{output}
        """


rule merge_annotations:
    input:
        ids="data/interim/samples_aggv3_ids_tidy.tsv",
        affection="data/interim/samples_cat_rd_affection.tsv",
        relation="data/interim/samples_cat_rd_relation.tsv",
        proband="data/interim/samples_cat_rd_proband.tsv",
        dna="data/interim/samples_cat_dna_bams.tsv",
        rna="data/interim/samples_gel_rna_bams.tsv",
        eq="data/interim/samples_cat_solved_eq.tsv",
        dx_discovery="data/interim/samples_gel_solved_dd.txt",
        hpo="data/interim/samples_cat_hpo.tsv",
    output:
        "data/final/merged_annotations.tsv",
    log:
        log_path("merge_annotations", workflow.snakefile),
    script:
        "merge_annotations.py"


rule all:
    default_target: True
    input:
        "data/final/aggv3_samples.txt",
        "data/final/merged_annotations.tsv",
